# Generated by Django 4.0.1 on 2022-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_link',
            field=models.CharField(default='No link', max_length=255),
        ),
    ]
